### ISSUE TITLE
Cannot read property 'invalid' of undefined

### ISSUE THREAD

**Issue by alonehover** [icaife/tailor#4]
run `tailor` error

mac os 10.13.3

```
/usr/local/lib/node_modules/tf-tailor/node_modules/_webpack-dev-middleware@3.0.1@webpack-dev-middleware/lib/context.js:95
  context.compiler.hooks.invalid.tap('WebpackDevMiddleware', invalid);
                         ^

TypeError: Cannot read property 'invalid' of undefined
    at ctx (/usr/local/lib/node_modules/tf-tailor/node_modules/_webpack-dev-middleware@3.0.1@webpack-dev-middleware/lib/context.js:95:26)
    at wdm (/usr/local/lib/node_modules/tf-tailor/node_modules/_webpack-dev-middleware@3.0.1@webpack-dev-middleware/index.js:44:19)
    at run (/usr/local/lib/node_modules/tf-tailor/server/server.js:23:25)
    at run (/usr/local/lib/node_modules/tf-tailor/index.js:49:3)
    at Object.<anonymous> (/usr/local/lib/node_modules/tf-tailor/bin/tailor.js:125:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3

```

[webpack-dev-middleware@3 requires webpack@4.](https://github.com/webpack/webpack-dev-middleware/issues/283#issuecomment-375007162)

**Comment by icaife** [comment]
fiexed, downgrade webpack-dev-middleware to 2.0.6

**Comment by luis-wang** [comment]
@icaife thank you very much!!
